## Adquisición y preprocesamiento de la información

<table>
    <tr>
      <td>Grado en Ingeniería de Datos e Inteligencia Artificial - Facultad de Informática - UCM
      </td>
      <td>
      <img src="https://biblioteca.ucm.es/data/cont/media/www/pag-88746//escudo.jpg"  width=50/>
      </td>
     </tr>
</table>




### Práctica 5 -Solución

Comenzamos cargando algunos módulos que nos van a venir bien

In [1]:
pip install --user --upgrade geopy

Requirement already satisfied: geopy in c:\users\rafa\appdata\roaming\python\python38\site-packages (2.3.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\rafa\appdata\roaming\python\python38\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ymongo (c:\users\rafa\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\rafa\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\rafa\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\rafa\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\rafa\appdata\roaming\python\python38\site-packages)
WARNING: Ignoring invalid distribution -ymongo (c:\users\rafa\appdata\roaming\python\python38\site-packages)

In [2]:
modules = ["geopy","folium","pprint"]


import sys
import os.path
from subprocess import check_call
import importlib
import os

def instala(modules):
    print("Instalando módulos")
    for m in modules:
        # para el import quitamos [...] y ==...
        p = m.find("[")
        mi = m if p==-1 else m[:p]
        p = mi.find("==")
        mi = mi if p==-1 else mi[:p]
        torch_loader = importlib.util.find_spec(mi)
        if torch_loader is not None:
            print(m," encontrado")
        else:
            print(m," No encontrado, instalando...",end="")  
            try:        
                r = check_call([sys.executable, "-m", "pip", "install", "--user", m])
                print("¡hecho!")
            except:
                print("¡Problema al instalar ",m,"! ¿seguro que el módulo existe?",sep="")

    print("¡Terminado!")

instala(modules)

Instalando módulos
geopy  encontrado
folium  encontrado
pprint  encontrado
¡Terminado!

Para mostrar dataframes uno al lado de otro

In [3]:
from IPython.display import display, HTML
from IPython.display import display_html
from IPython.display import Markdown

def display_side_by_side(*args,title=""):
    print(title)
    html_str = ''
    for df in args:
        html_str += '&nbsp;&nbsp;&nbsp;'+df.to_html()
    display_html(
        html_str.replace('table','table style="display:inline"'), 
        raw=True)

## Funciones 

A partir de ahora vamos a definir nuestras propias funciones. Aparte del uso habitual de encapsulación y reusabilidad, en ingeniería de datos van a ser útiles para hacer operaciones complejas sobre dataframes.

En un ejemplo sencillo de función sin parámetros que devuelve directamente un valor:

In [4]:
from pathlib import Path
def get_path():
    return Path.cwd() 

### llamada a la función
path = get_path()
path

WindowsPath('d:/docencia/2223/APD/pruebas')

Otro ejemplo un poco más interesante: la función recibe una url como parámetro y devuelve un dataframe después de cargarlo y hacer algo de preprocesamiento simple:

In [5]:
import pandas as pd

# lee el fichero con opinión de usuarios sobre los candidatos Clinton y Trump en las elecciones americanas de 2016
def lee_usa(url):
    df = pd.read_csv(url).iloc[:,1:]   # df es una variable local de la función
    df.columns = ["id","clinton","trump"]
    return df

### llamada a la función
url="https://github.com/RafaelCaballero/tdm/raw/master/datos/user10CT.zip"
df_usa = lee_usa(url)
df_usa

                        id   clinton     trump
0       729822791747444737 -0.567568  0.415094
1               3438745348 -0.666667 -0.111111
2               1167485504 -0.466667  0.500000
3                219793074 -0.729730  0.620370
4               4605113535 -0.586207  0.373832
...                    ...       ...       ...
161168           118676558  0.000000  0.000000
161169          1438467932  0.857143  0.000000
161170  772542459901571072 -0.583333  0.000000
161171          3833168952 -0.400000  0.000000
161172  797601605449154560  0.017241  0.000000

[161173 rows x 3 columns]

En ocasiones las funciones no devuelven nada, no tienen `return`. Cuando esto sucede es porque la función tiene "efectos laterales": por ejemplo crear una carpeta o, como en este caso, mostrar por pantalla el contenido de una carpeta

In [6]:

# lista los ficheros y subcarpetas del path
def lista(path):
    print(path)
    espacio = " "*5
    for p in path.iterdir():
        if p.is_dir():
            print(espacio,p.name,": carpeta",sep="")
        else:
            if p.is_file():
                print(espacio,p.name,": fichero",sep="")
    print("="*40)
                
#### llamada
lista(path)

d:\docencia\2223\APD\pruebas
     .cache: fichero
     .ipynb_checkpoints: carpeta
     A.csv: fichero
     B.csv: fichero
     BeautifulSoup-Copy1.ipynb: fichero
     BeautifulSoup.ipynb: fichero
     C.csv: fichero
     cancion.mp3: fichero
     datosparo.ipynb: fichero
     IMDB.ipynb: fichero
     mapa.ipynb: fichero
     meltExample.ipynb: fichero
     practica1Sol.ipynb: fichero
     practica3sol.ipynb: fichero
     raw: carpeta
     repartidos: carpeta
     requiem.mp3: fichero
     satelites.ipynb: fichero
     spotifySol.ipynb: fichero
     top_25_pandas_tricks.ipynb: fichero
     Untitled.ipynb: fichero
     Untitled1.ipynb: fichero
     Untitled2.ipynb: fichero
     Untitled3.ipynb: fichero
     usa.ipynb: fichero
========================================

**Ejercicio 1**
A partir de la solución de la pregunta 1 en la práctica 4 escribir una función que reciba 2 parámetros:

*Nombre*: `crea_carpetas(path,folders)`
- `path`: el path donde se quieren crear subcarpetas
- `folders`: una lista de subcarpetas a crear en el path.

*Salida*: no devuelve nada, solo crea las subcarpetas dentro del path si no existen

In [7]:
## Solución 
def crea_carpetas(path,folders):
    for f in folders:
        newFolder = Path(path,f)
        newFolder.mkdir(exist_ok=True,parents=True)

#### no modificar de aquí hacia abajo
# llamada 
crea_carpetas(path,["raw","repartidos"])
# para probar
lista(path)

d:\docencia\2223\APD\pruebas
     .cache: fichero
     .ipynb_checkpoints: carpeta
     A.csv: fichero
     B.csv: fichero
     BeautifulSoup-Copy1.ipynb: fichero
     BeautifulSoup.ipynb: fichero
     C.csv: fichero
     cancion.mp3: fichero
     datosparo.ipynb: fichero
     IMDB.ipynb: fichero
     mapa.ipynb: fichero
     meltExample.ipynb: fichero
     practica1Sol.ipynb: fichero
     practica3sol.ipynb: fichero
     raw: carpeta
     repartidos: carpeta
     requiem.mp3: fichero
     satelites.ipynb: fichero
     spotifySol.ipynb: fichero
     top_25_pandas_tricks.ipynb: fichero
     Untitled.ipynb: fichero
     Untitled1.ipynb: fichero
     Untitled2.ipynb: fichero
     Untitled3.ipynb: fichero
     usa.ipynb: fichero
========================================

**Ejercicio 2** Escribir una función

*Nombre*: `descarga(path,url)`
- `path`: el path donde se alojará el fichero descargado, incluye el nombre local del fichero
- `url`: la url de un fichero

*Salida*: no devuelve nada, solo descarga usando requests el fichero indicado

Pista: en la solución de la práctica 4, ejercicio 2, podemos ver un ejemplo de descarga

In [8]:
import requests

# solución
def descarga(path,url):
    r = requests.get(url, allow_redirects=True) # el fichero queda en la variable r
    if r.status_code == 200:
        with open(path, 'wb') as f:
            f.write(r.content) # ahora lo grabamos localmente
    else:
        print("Error ",r.status_code)

# no tocar a partir de aquí, es para probar descargando dos ficheros, clientes.csv y gestores.csv que vamos a usar a continuación
url_clientes = "https://raw.githubusercontent.com/RafaelCaballero/tdm/master/datos/clientes2.csv"  
path_raw = Path(path,"raw")
path_clientes = Path(path_raw,"clientes.csv")
descarga(path_clientes,url_clientes)
path_gestores = Path(path_raw,"gestores.csv")
url_gestores = "https://raw.githubusercontent.com/RafaelCaballero/tdm/master/datos/clientegestor.csv"
descarga(path_gestores,url_gestores)
lista(path_raw)

d:\docencia\2223\APD\pruebas\raw
     abr_meteo22.csv: fichero
     ago_meteo22.csv: fichero
     clientes.csv: fichero
     dic_meteo22.csv: fichero
     download: carpeta
     ene_meteo22.csv: fichero
     feb_meteo22.csv: fichero
     gestores.csv: fichero
     Interpretación_datos_meteorologicos.pdf: fichero
     jul_meteo22.csv: fichero
     jun_meteo22.csv: fichero
     mar_meteo22.csv: fichero
     may_meteo22.csv: fichero
     nov_meteo22.csv: fichero
     oct_meteo22.csv: fichero
     readme.txt: fichero
     sep_meteo22.csv: fichero
========================================

**Ejercicio 3** Empezamos cargando los dos ficheros que acabamos de descargar:

In [9]:
df_clientes = pd.read_csv(path_clientes)
df_gestores = pd.read_csv(path_gestores)
display_side_by_side(df_clientes,df_gestores)

Escribir código para generar un nuevo dataframe `df_gc` que combine los dos dataframes añadiendo a los datos de `df_clientes` su gestor. Si un cliente no tiene gestor se eliminará del resultado (igualmente no aparecerán gestores que no sean de clientes en `df_clientes`)

In [10]:
df_gc = pd.merge(df_clientes,df_gestores)
# para probar
df_gc

     cliente  documento  entregado  tasas gestor
0    2910167    1687488          0    464      A
1    2910167     684909          0    125      A
2    2910167     796437          1    914      A
3    2910167    1268173          1    787      A
4    2910167    1468405          1    222      A
..       ...        ...        ...    ...    ...
495  4225453     746041          1    718      A
496  4225453     389625          0    506      A
497  4225453     234715          0    785      A
498  4225453     770521          1    836      A
499  4225453    1835650          1    851      A

[500 rows x 5 columns]

In [11]:
df_gc.gestor.value_counts()

A    244
B    154
C    102
Name: gestor, dtype: int64

**Ejercicio 4** (2 puntos) Queremos repartir el dataframe df_gc en varios, uno por cada gestor, que además se grabarán en la carpeta `repartidos` con nombre del gestor (y extensión csv). Escribir una función 

*Nombre*: `reparte(path,df)`
- `path`: el path de una carpeta donde se alojarán los nuevos ficheros creados a partir de df, uno por gestor
- `df`: el dataframe a repartir en varios, debe incluir una columna `gestor`que se usara para repartir

*Salida*: no devuelve nada, solo descarga usando requests el fichero indicado

Idea: para cada valor diferente de la columna gestor (usar un `for`) se usara yun filtro para las filas del gestor. Se aplicará el filtro para obtener un dataframe nuevo con los datos del gestor, que a continuación se grabará en la carpeta indicada

In [12]:
# solución
def reparte(path,df):
    for g in df.gestor.unique():
        print(g)
        path_g = Path(path,g+".csv")
        filtro_g = df.gestor==g
        df_g  = df[filtro_g]
        df_g.to_csv(path_g,index=False)
        
## llamada         
path_repartidos = Path(path,"repartidos")
reparte(path_repartidos,df_gc)
# para comprobar
lista(path_repartidos)

A
B
C
d:\docencia\2223\APD\pruebas\repartidos
     A.csv: fichero
     B.csv: fichero
     C.csv: fichero
========================================

**Ejercicio 5** Recordamos el dataframe df_usa con opiniones de usuarios de Twitter sobre los candidatos de 2016

In [13]:

df_usa

                        id   clinton     trump
0       729822791747444737 -0.567568  0.415094
1               3438745348 -0.666667 -0.111111
2               1167485504 -0.466667  0.500000
3                219793074 -0.729730  0.620370
4               4605113535 -0.586207  0.373832
...                    ...       ...       ...
161168           118676558  0.000000  0.000000
161169          1438467932  0.857143  0.000000
161170  772542459901571072 -0.583333  0.000000
161171          3833168952 -0.400000  0.000000
161172  797601605449154560  0.017241  0.000000

[161173 rows x 3 columns]

En cada fila `clinton`, `trump` corresponden a la opinión media sobre los candidatos Clinton y Trump que tuvo el usuario de id `id`en la campaña para las elecciones USA 2016. Tanto clinton como trump van de -1 (opinión totalmente negativa) a +1 totalmente positiva.
Queremos crear un columna nueva C2 que valga -1 para las filas con clinton<0, +1 para las filas con clinton>0 y 0 si clinton==0. Una forma de hacerlo es crear la columna con un valor inicial y luego cambiar con filtros este valor inicial para que tome el que queremos

In [14]:
df_usa["C2"] = 0 # la inicializamos a 0 
df_usa

                        id   clinton     trump  C2
0       729822791747444737 -0.567568  0.415094   0
1               3438745348 -0.666667 -0.111111   0
2               1167485504 -0.466667  0.500000   0
3                219793074 -0.729730  0.620370   0
4               4605113535 -0.586207  0.373832   0
...                    ...       ...       ...  ..
161168           118676558  0.000000  0.000000   0
161169          1438467932  0.857143  0.000000   0
161170  772542459901571072 -0.583333  0.000000   0
161171          3833168952 -0.400000  0.000000   0
161172  797601605449154560  0.017241  0.000000   0

[161173 rows x 4 columns]

Completar el código para que C2 tome los valores que deseamos usando filtros

Pista: `df_usa.loc[filtro,"C2"]` accede a la columna "C2" de las filas de `df_usa` que verifican el filtro

In [15]:
# solución
filtronegativo = df_usa.clinton<0
filtropositivo = df_usa.clinton>0

df_usa.loc[filtronegativo,"C2"] = -1
df_usa.loc[filtropositivo,"C2"] = +1

# para probar
df_usa

                        id   clinton     trump  C2
0       729822791747444737 -0.567568  0.415094  -1
1               3438745348 -0.666667 -0.111111  -1
2               1167485504 -0.466667  0.500000  -1
3                219793074 -0.729730  0.620370  -1
4               4605113535 -0.586207  0.373832  -1
...                    ...       ...       ...  ..
161168           118676558  0.000000  0.000000   0
161169          1438467932  0.857143  0.000000   1
161170  772542459901571072 -0.583333  0.000000  -1
161171          3833168952 -0.400000  0.000000  -1
161172  797601605449154560  0.017241  0.000000   1

[161173 rows x 4 columns]

### map

El método anterior para crear una columna nueva puede llegar a ser muy complicado; por ello se suele usar `map`. Vamos a verlo para hacer algo análogo con la columna T2

La idea es la siguiente: primero se escribe una función en Python que devuelva el valor nuevo de la columna T2 para un valor concreto de T (es la idea de siempre, pensar en números y luego extender a columnas/filas)

In [16]:
def posneg(t):
    if t<0:
        res=-1
    elif t==0:
        res=0
    else:
        res=+1
    return res

# para probar
print("-0.85 --> ",posneg(-0.85))
print("+0.15 --> ",posneg(+0.15))
print("+0 --> ",posneg(+0))

-0.85 -->  -1
+0.15 -->  1
+0 -->  0


Una vez que hemos visto que funciona ya podemos crear la nueva columna T2 que será el resultado de aplicar la función `posneg` a cada valor de la columna T, uno a uno. La función `map` de `Series`nos permite hacer eso

In [17]:
df_usa["T2"] = df_usa.trump.map(posneg)
df_usa

                        id   clinton     trump  C2  T2
0       729822791747444737 -0.567568  0.415094  -1   1
1               3438745348 -0.666667 -0.111111  -1  -1
2               1167485504 -0.466667  0.500000  -1   1
3                219793074 -0.729730  0.620370  -1   1
4               4605113535 -0.586207  0.373832  -1   1
...                    ...       ...       ...  ..  ..
161168           118676558  0.000000  0.000000   0   0
161169          1438467932  0.857143  0.000000   1   0
161170  772542459901571072 -0.583333  0.000000  -1   0
161171          3833168952 -0.400000  0.000000  -1   0
161172  797601605449154560  0.017241  0.000000   1   0

[161173 rows x 5 columns]

**Ejercicio 6** [2 puntos] Consideramos ahora el siguiente dataframe con datos de usuarios en Twitter

In [18]:
url = "https://raw.githubusercontent.com/RafaelCaballero/tdm/master/datos/user_coords.csv"
import pandas as pd
df_coord = pd.read_csv(url).drop(columns=["level_0","index"])
df_coord

,_id,followers,location,screen_name,verified,long,lat
0,148076807,515,"19.447297,-70.678351",eugenio_sky,False,-3.685060,40.427170
1,557076972,1022,BCN,annetapedro,False,2.176402,41.405603
2,800430827947442176,20,"Valencia, España",Trastarteando,False,-0.293131,39.567629
3,1187834312,653,"Madrid, Spain",manukareol,False,-3.705050,40.438520
4,3153928585,99,"Málaga, Andalucía",PedroMendez_mlg,False,-4.407480,36.720087
5,18901057,1562,UK/Brasil/España,GuitarCafe,False,0.060693,40.052917
6,117884436,1502,Barcelona,Ldiazalonso,False,-3.707360,40.421380
7,761237429072388096,35,"Madrid, Comunidad de Madrid",fjdemi,False,-3.584300,40.360320
8,184959473,733,LA MANCHA y SEVILLA,DonaireAlberto,False,-3.930790,38.986850
9,2838312285,27,España,begonabotana,False,-8.410720,43.355270
10,984999942,1239,Elche,DeportesSinAdje,False,-0.495255,38.354110
11,287826955,2244,Salamanca,AlexLorrys,False,-5.665297,40.995588
12,292027758,2442,madrid (españa),juanemilioma,False,-3.703560,40.413900
13,459477808,697,Estadio de Riazor,carrinho_7,False,-8.417591,43.368882
14,875433438,491,"De Salamanca, en Madrid",veracoteloc,False,-3.682013,40.413704
15,89165765,27536,Madrid,martuniki,True,-3.555100,40.423200
16,2378742043,106,valencia,alvarotriatlon,False,-0.332990,39.569176
17,701379658600882176,168,"Elche, España",juancaitan999,False,-0.744040,38.227070
18,42004114,2340,"Canary Islands, Spain",sheilacrosby403,False,-17.775510,28.641670
19,299264539,147,"Santa Cruz de Tenerife, España",cocinadedolores,False,-16.506800,28.413808
20,96663968,1394,"Budapest, Hungría",GGabrielaH,False,-3.709150,40.419110
21,913311027407802368,44,"Madrid, España",Xoroto82,False,-3.555100,40.423200
22,180333341,413,"Valencia, España",_albertt_,False,-3.696575,40.416390
23,1974659378,2198,Barcelona,sr_boca,False,2.153530,41.394350
24,745651197286162432,203,"Carmona, España",Santa_MartaSL,False,-5.646853,37.481902
25,92629354,981,"Zaragoza, España",javinumy,False,-0.903900,41.634790
26,4069778056,702,"Madrid, Spain",eliaonmymind,False,4.242396,39.820458
27,996055734,475,Móstoles-Madrid/Orihuela Costa,LidiaMP_12,False,-3.575250,40.207000
28,278039896,241,Barcelona,capitanspavento,False,2.167317,41.375952
29,118352921,2961,"Madrid ,Spain",fvazquezmedem,False,-3.684590,40.427830
30,270010775,39,Felgosas-A Coruña,ReinaldoReini,False,-8.285718,43.315855
31,184537316,408,PARAGUAY,miguelx94,False,-8.176534,43.496028
32,1580184631,102,Elche.,josevcanales,False,-0.643128,38.219706
33,719905537396228096,706,"Mijas, Spain",AlanDreezer,False,-4.673660,36.555811
34,1495328876,763,"Madrid, Comunidad de Madrid",Pablocarroglez,False,-3.746949,40.322687
35,246837853,2480,Madrid,Kutxi_Pacheco,False,-3.700420,40.440970
36,142451580,52,Madrid,murcianicaguapa,False,-8.782765,42.264213
37,709714971,872,"Málaga, España",MarPadilla_,False,-4.461353,36.666172
38,15703541,5084,"Washington, D.C.",wbdnewton,False,-3.707360,40.421380
39,1553476147,214,Madrid - Spain,MuchoFunkSpain,False,-3.457420,40.446570
40,849681349162283008,217,"Principado de Asturias, España",sparacingfoto,False,-3.686452,43.388387
41,757471410,324,"Glasgow, Scotland",20_Tina_Torres,False,-3.711527,40.422560
42,1122025458,846,"A Coruña, España",acasar51,False,-8.264650,43.322800
43,233345061,2437,Albacete,A_MtnezIniesta,False,-3.692180,40.419010
44,1723462104,103,"Torrent, Valencia",adolvale,False,-0.466667,39.433300
45,84143687,1814,Madrid - Cáceres,Alpaniagu,False,-3.703260,40.464447
46,106841104,90,Cuidotumascota.com,OLKI69,False,-3.584300,40.360320
47,943230391,64,Arteixo,chelodxastre,False,-8.401650,43.369760
48,1337479172441169920,1328,"Sevilla, España",CajonSevillano,False,-5.990828,37.389712
49,446433608,924,Villalba Sity,SandraAyuso_,False,-3.985473,40.644887
50,490529286,431,JLAM ∞,likeblueskies,False,-3.656678,40.520858
51,3352643962,256,"Valencia, España",alexvelasco943,False,0.050000,38.650000
52,799512942,1149,"Las Palmas, Islas Canarias",BombonKarol,False,-17.980833,27.641944

Añadir a `df_coord` nueva columna `muchos_followers` que valga "Sí" si el número de followers es mayor 1000 o "No" en otro caso. Hacerlo en dos pasos.

a) Escribir una función de Pythom `muchos` que reciba como parámetro un valor n y devuelva "Sí" si n>1000, y "No" en otro caso

In [19]:
def muchos(n): #completar
    if n>1000:
        res="Sí"
    else:
        res="No"
    return res
    
# para probar  
print("muchos(2000)",muchos(2000)) # Sí
print("muchos(500)",muchos(500)) # No
print("muchos(1000)",muchos(1000)) # No

muchos(2000) Sí
muchos(500) No
muchos(1000) No

b) Aplicar con `map`la función a todos los elementos de `followers` para crear la columna `muchos_followers` en `df_coord`

In [20]:
# solución
df_coord["muchos_followers"] = df_coord.followers.map(muchos)

# para comprobar
df_coord

,_id,followers,location,screen_name,verified,long,lat,muchos_followers
0,148076807,515,"19.447297,-70.678351",eugenio_sky,False,-3.685060,40.427170,No
1,557076972,1022,BCN,annetapedro,False,2.176402,41.405603,Sí
2,800430827947442176,20,"Valencia, España",Trastarteando,False,-0.293131,39.567629,No
3,1187834312,653,"Madrid, Spain",manukareol,False,-3.705050,40.438520,No
4,3153928585,99,"Málaga, Andalucía",PedroMendez_mlg,False,-4.407480,36.720087,No
5,18901057,1562,UK/Brasil/España,GuitarCafe,False,0.060693,40.052917,Sí
6,117884436,1502,Barcelona,Ldiazalonso,False,-3.707360,40.421380,Sí
7,761237429072388096,35,"Madrid, Comunidad de Madrid",fjdemi,False,-3.584300,40.360320,No
8,184959473,733,LA MANCHA y SEVILLA,DonaireAlberto,False,-3.930790,38.986850,No
9,2838312285,27,España,begonabotana,False,-8.410720,43.355270,No
10,984999942,1239,Elche,DeportesSinAdje,False,-0.495255,38.354110,Sí
11,287826955,2244,Salamanca,AlexLorrys,False,-5.665297,40.995588,Sí
12,292027758,2442,madrid (españa),juanemilioma,False,-3.703560,40.413900,Sí
13,459477808,697,Estadio de Riazor,carrinho_7,False,-8.417591,43.368882,No
14,875433438,491,"De Salamanca, en Madrid",veracoteloc,False,-3.682013,40.413704,No
15,89165765,27536,Madrid,martuniki,True,-3.555100,40.423200,Sí
16,2378742043,106,valencia,alvarotriatlon,False,-0.332990,39.569176,No
17,701379658600882176,168,"Elche, España",juancaitan999,False,-0.744040,38.227070,No
18,42004114,2340,"Canary Islands, Spain",sheilacrosby403,False,-17.775510,28.641670,Sí
19,299264539,147,"Santa Cruz de Tenerife, España",cocinadedolores,False,-16.506800,28.413808,No
20,96663968,1394,"Budapest, Hungría",GGabrielaH,False,-3.709150,40.419110,Sí
21,913311027407802368,44,"Madrid, España",Xoroto82,False,-3.555100,40.423200,No
22,180333341,413,"Valencia, España",_albertt_,False,-3.696575,40.416390,No
23,1974659378,2198,Barcelona,sr_boca,False,2.153530,41.394350,Sí
24,745651197286162432,203,"Carmona, España",Santa_MartaSL,False,-5.646853,37.481902,No
25,92629354,981,"Zaragoza, España",javinumy,False,-0.903900,41.634790,No
26,4069778056,702,"Madrid, Spain",eliaonmymind,False,4.242396,39.820458,No
27,996055734,475,Móstoles-Madrid/Orihuela Costa,LidiaMP_12,False,-3.575250,40.207000,No
28,278039896,241,Barcelona,capitanspavento,False,2.167317,41.375952,No
29,118352921,2961,"Madrid ,Spain",fvazquezmedem,False,-3.684590,40.427830,Sí
30,270010775,39,Felgosas-A Coruña,ReinaldoReini,False,-8.285718,43.315855,No
31,184537316,408,PARAGUAY,miguelx94,False,-8.176534,43.496028,No
32,1580184631,102,Elche.,josevcanales,False,-0.643128,38.219706,No
33,719905537396228096,706,"Mijas, Spain",AlanDreezer,False,-4.673660,36.555811,No
34,1495328876,763,"Madrid, Comunidad de Madrid",Pablocarroglez,False,-3.746949,40.322687,No
35,246837853,2480,Madrid,Kutxi_Pacheco,False,-3.700420,40.440970,Sí
36,142451580,52,Madrid,murcianicaguapa,False,-8.782765,42.264213,No
37,709714971,872,"Málaga, España",MarPadilla_,False,-4.461353,36.666172,No
38,15703541,5084,"Washington, D.C.",wbdnewton,False,-3.707360,40.421380,Sí
39,1553476147,214,Madrid - Spain,MuchoFunkSpain,False,-3.457420,40.446570,No
40,849681349162283008,217,"Principado de Asturias, España",sparacingfoto,False,-3.686452,43.388387,No
41,757471410,324,"Glasgow, Scotland",20_Tina_Torres,False,-3.711527,40.422560,No
42,1122025458,846,"A Coruña, España",acasar51,False,-8.264650,43.322800,No
43,233345061,2437,Albacete,A_MtnezIniesta,False,-3.692180,40.419010,Sí
44,1723462104,103,"Torrent, Valencia",adolvale,False,-0.466667,39.433300,No
45,84143687,1814,Madrid - Cáceres,Alpaniagu,False,-3.703260,40.464447,Sí
46,106841104,90,Cuidotumascota.com,OLKI69,False,-3.584300,40.360320,No
47,943230391,64,Arteixo,chelodxastre,False,-8.401650,43.369760,No
48,1337479172441169920,1328,"Sevilla, España",CajonSevillano,False,-5.990828,37.389712,Sí
49,446433608,924,Villalba Sity,SandraAyuso_,False,-3.985473,40.644887,No
50,490529286,431,JLAM ∞,likeblueskies,False,-3.656678,40.520858,No
51,3352643962,256,"Valencia, España",alexvelasco943,False,0.050000,38.650000,No
52,799512942,1149,"Las Palmas, Islas Canarias",BombonKarol,False,-17.980833,27.641944,Sí

### apply 
`map` es muy útil, pero a veces resulta insuficiente. Supongamos que ahora en df_usa queremos añadir una columna "voto" que indique si el usuario es "Pro-trump" (trump>clinton), "pro-clinton" (clinton<trump) o "neutro". El problema es que ahora no podemos usar map porque se aplica a una columna y nuestra nueva columna depende de 2, trump y clinton. 

Por fortuna `apply` nos permite aplicar una función a una fila entera.

In [21]:
df_usa

                        id   clinton     trump  C2  T2
0       729822791747444737 -0.567568  0.415094  -1   1
1               3438745348 -0.666667 -0.111111  -1  -1
2               1167485504 -0.466667  0.500000  -1   1
3                219793074 -0.729730  0.620370  -1   1
4               4605113535 -0.586207  0.373832  -1   1
...                    ...       ...       ...  ..  ..
161168           118676558  0.000000  0.000000   0   0
161169          1438467932  0.857143  0.000000   1   0
161170  772542459901571072 -0.583333  0.000000  -1   0
161171          3833168952 -0.400000  0.000000  -1   0
161172  797601605449154560  0.017241  0.000000   1   0

[161173 rows x 5 columns]

In [22]:
def pro(row): 
    #print(row)
    if row["trump"]>row["clinton"]:
        res="Pro-trump"
    elif row["trump"]<row["clinton"]:
        res="Pro-clinton"
    else:
        res="neutro"
    return(res)
        
pro(df_usa.iloc[0])

'Pro-trump'

Aplicamos la función

In [23]:
df_usa["voto"] = df_usa.apply(pro,axis=1) # obsérvese que ahora no se aplica a una columna sino al dataframe entero
df_usa

                        id   clinton     trump  C2  T2         voto
0       729822791747444737 -0.567568  0.415094  -1   1    Pro-trump
1               3438745348 -0.666667 -0.111111  -1  -1    Pro-trump
2               1167485504 -0.466667  0.500000  -1   1    Pro-trump
3                219793074 -0.729730  0.620370  -1   1    Pro-trump
4               4605113535 -0.586207  0.373832  -1   1    Pro-trump
...                    ...       ...       ...  ..  ..          ...
161168           118676558  0.000000  0.000000   0   0       neutro
161169          1438467932  0.857143  0.000000   1   0  Pro-clinton
161170  772542459901571072 -0.583333  0.000000  -1   0    Pro-trump
161171          3833168952 -0.400000  0.000000  -1   0    Pro-trump
161172  797601605449154560  0.017241  0.000000   1   0  Pro-clinton

[161173 rows x 6 columns]

**Ejercicio 7** (2 puntos) En `df_coord` añadir una columna `coords` que contendrá un string de la forma "lat, long" para cada pareja de coordenadas

In [24]:
df_coord

,_id,followers,location,screen_name,verified,long,lat,muchos_followers
0,148076807,515,"19.447297,-70.678351",eugenio_sky,False,-3.685060,40.427170,No
1,557076972,1022,BCN,annetapedro,False,2.176402,41.405603,Sí
2,800430827947442176,20,"Valencia, España",Trastarteando,False,-0.293131,39.567629,No
3,1187834312,653,"Madrid, Spain",manukareol,False,-3.705050,40.438520,No
4,3153928585,99,"Málaga, Andalucía",PedroMendez_mlg,False,-4.407480,36.720087,No
5,18901057,1562,UK/Brasil/España,GuitarCafe,False,0.060693,40.052917,Sí
6,117884436,1502,Barcelona,Ldiazalonso,False,-3.707360,40.421380,Sí
7,761237429072388096,35,"Madrid, Comunidad de Madrid",fjdemi,False,-3.584300,40.360320,No
8,184959473,733,LA MANCHA y SEVILLA,DonaireAlberto,False,-3.930790,38.986850,No
9,2838312285,27,España,begonabotana,False,-8.410720,43.355270,No
10,984999942,1239,Elche,DeportesSinAdje,False,-0.495255,38.354110,Sí
11,287826955,2244,Salamanca,AlexLorrys,False,-5.665297,40.995588,Sí
12,292027758,2442,madrid (españa),juanemilioma,False,-3.703560,40.413900,Sí
13,459477808,697,Estadio de Riazor,carrinho_7,False,-8.417591,43.368882,No
14,875433438,491,"De Salamanca, en Madrid",veracoteloc,False,-3.682013,40.413704,No
15,89165765,27536,Madrid,martuniki,True,-3.555100,40.423200,Sí
16,2378742043,106,valencia,alvarotriatlon,False,-0.332990,39.569176,No
17,701379658600882176,168,"Elche, España",juancaitan999,False,-0.744040,38.227070,No
18,42004114,2340,"Canary Islands, Spain",sheilacrosby403,False,-17.775510,28.641670,Sí
19,299264539,147,"Santa Cruz de Tenerife, España",cocinadedolores,False,-16.506800,28.413808,No
20,96663968,1394,"Budapest, Hungría",GGabrielaH,False,-3.709150,40.419110,Sí
21,913311027407802368,44,"Madrid, España",Xoroto82,False,-3.555100,40.423200,No
22,180333341,413,"Valencia, España",_albertt_,False,-3.696575,40.416390,No
23,1974659378,2198,Barcelona,sr_boca,False,2.153530,41.394350,Sí
24,745651197286162432,203,"Carmona, España",Santa_MartaSL,False,-5.646853,37.481902,No
25,92629354,981,"Zaragoza, España",javinumy,False,-0.903900,41.634790,No
26,4069778056,702,"Madrid, Spain",eliaonmymind,False,4.242396,39.820458,No
27,996055734,475,Móstoles-Madrid/Orihuela Costa,LidiaMP_12,False,-3.575250,40.207000,No
28,278039896,241,Barcelona,capitanspavento,False,2.167317,41.375952,No
29,118352921,2961,"Madrid ,Spain",fvazquezmedem,False,-3.684590,40.427830,Sí
30,270010775,39,Felgosas-A Coruña,ReinaldoReini,False,-8.285718,43.315855,No
31,184537316,408,PARAGUAY,miguelx94,False,-8.176534,43.496028,No
32,1580184631,102,Elche.,josevcanales,False,-0.643128,38.219706,No
33,719905537396228096,706,"Mijas, Spain",AlanDreezer,False,-4.673660,36.555811,No
34,1495328876,763,"Madrid, Comunidad de Madrid",Pablocarroglez,False,-3.746949,40.322687,No
35,246837853,2480,Madrid,Kutxi_Pacheco,False,-3.700420,40.440970,Sí
36,142451580,52,Madrid,murcianicaguapa,False,-8.782765,42.264213,No
37,709714971,872,"Málaga, España",MarPadilla_,False,-4.461353,36.666172,No
38,15703541,5084,"Washington, D.C.",wbdnewton,False,-3.707360,40.421380,Sí
39,1553476147,214,Madrid - Spain,MuchoFunkSpain,False,-3.457420,40.446570,No
40,849681349162283008,217,"Principado de Asturias, España",sparacingfoto,False,-3.686452,43.388387,No
41,757471410,324,"Glasgow, Scotland",20_Tina_Torres,False,-3.711527,40.422560,No
42,1122025458,846,"A Coruña, España",acasar51,False,-8.264650,43.322800,No
43,233345061,2437,Albacete,A_MtnezIniesta,False,-3.692180,40.419010,Sí
44,1723462104,103,"Torrent, Valencia",adolvale,False,-0.466667,39.433300,No
45,84143687,1814,Madrid - Cáceres,Alpaniagu,False,-3.703260,40.464447,Sí
46,106841104,90,Cuidotumascota.com,OLKI69,False,-3.584300,40.360320,No
47,943230391,64,Arteixo,chelodxastre,False,-8.401650,43.369760,No
48,1337479172441169920,1328,"Sevilla, España",CajonSevillano,False,-5.990828,37.389712,Sí
49,446433608,924,Villalba Sity,SandraAyuso_,False,-3.985473,40.644887,No
50,490529286,431,JLAM ∞,likeblueskies,False,-3.656678,40.520858,No
51,3352643962,256,"Valencia, España",alexvelasco943,False,0.050000,38.650000,No
52,799512942,1149,"Las Palmas, Islas Canarias",BombonKarol,False,-17.980833,27.641944,Sí

En la primera fila, por ejemplo, la columna valdrá "40.427170 , -3.685060". Utilizar `apply`y una función auxiliar
`prepara_coords`.

Pista: recordar que str(x) convirte el número x e un string

In [25]:
def prepara_coords(row): #completar
    return str(row["lat"])+", "+str(row["long"])
df_coord["coords"] = df_coord.apply(prepara_coords,axis=1)

# para comprobar
df_coord

,_id,followers,location,screen_name,verified,long,lat,muchos_followers,coords
0,148076807,515,"19.447297,-70.678351",eugenio_sky,False,-3.685060,40.427170,No,"40.42717, -3.68506"
1,557076972,1022,BCN,annetapedro,False,2.176402,41.405603,Sí,"41.40560346, 2.17640221"
2,800430827947442176,20,"Valencia, España",Trastarteando,False,-0.293131,39.567629,No,"39.5676291, -0.29313098"
3,1187834312,653,"Madrid, Spain",manukareol,False,-3.705050,40.438520,No,"40.43852, -3.70505"
4,3153928585,99,"Málaga, Andalucía",PedroMendez_mlg,False,-4.407480,36.720087,No,"36.72008667, -4.40747973"
5,18901057,1562,UK/Brasil/España,GuitarCafe,False,0.060693,40.052917,Sí,"40.05291748, 0.06069287"
6,117884436,1502,Barcelona,Ldiazalonso,False,-3.707360,40.421380,Sí,"40.42138, -3.70736"
7,761237429072388096,35,"Madrid, Comunidad de Madrid",fjdemi,False,-3.584300,40.360320,No,"40.36032, -3.5843"
8,184959473,733,LA MANCHA y SEVILLA,DonaireAlberto,False,-3.930790,38.986850,No,"38.9868499, -3.93079"
9,2838312285,27,España,begonabotana,False,-8.410720,43.355270,No,"43.35527, -8.41072"
10,984999942,1239,Elche,DeportesSinAdje,False,-0.495255,38.354110,Sí,"38.35411037, -0.4952552999999999"
11,287826955,2244,Salamanca,AlexLorrys,False,-5.665297,40.995588,Sí,"40.99558849, -5.66529737"
12,292027758,2442,madrid (españa),juanemilioma,False,-3.703560,40.413900,Sí,"40.4139, -3.70356"
13,459477808,697,Estadio de Riazor,carrinho_7,False,-8.417591,43.368882,No,"43.36888152, -8.4175908"
14,875433438,491,"De Salamanca, en Madrid",veracoteloc,False,-3.682013,40.413704,No,"40.41370364, -3.68201315"
15,89165765,27536,Madrid,martuniki,True,-3.555100,40.423200,Sí,"40.4232, -3.5551"
16,2378742043,106,valencia,alvarotriatlon,False,-0.332990,39.569176,No,"39.5691757, -0.3329904999999999"
17,701379658600882176,168,"Elche, España",juancaitan999,False,-0.744040,38.227070,No,"38.22707, -0.74404"
18,42004114,2340,"Canary Islands, Spain",sheilacrosby403,False,-17.775510,28.641670,Sí,"28.64167, -17.77551"
19,299264539,147,"Santa Cruz de Tenerife, España",cocinadedolores,False,-16.506800,28.413808,No,"28.41380848, -16.50680045"
20,96663968,1394,"Budapest, Hungría",GGabrielaH,False,-3.709150,40.419110,Sí,"40.41911, -3.70915"
21,913311027407802368,44,"Madrid, España",Xoroto82,False,-3.555100,40.423200,No,"40.4232, -3.5551"
22,180333341,413,"Valencia, España",_albertt_,False,-3.696575,40.416390,No,"40.41638978, -3.69657487"
23,1974659378,2198,Barcelona,sr_boca,False,2.153530,41.394350,Sí,"41.39435, 2.15353"
24,745651197286162432,203,"Carmona, España",Santa_MartaSL,False,-5.646853,37.481902,No,"37.4819022, -5.6468533"
25,92629354,981,"Zaragoza, España",javinumy,False,-0.903900,41.634790,No,"41.63479, -0.9039"
26,4069778056,702,"Madrid, Spain",eliaonmymind,False,4.242396,39.820458,No,"39.82045827, 4.24239635"
27,996055734,475,Móstoles-Madrid/Orihuela Costa,LidiaMP_12,False,-3.575250,40.207000,No,"40.207, -3.57525"
28,278039896,241,Barcelona,capitanspavento,False,2.167317,41.375952,No,"41.37595159, 2.16731653"
29,118352921,2961,"Madrid ,Spain",fvazquezmedem,False,-3.684590,40.427830,Sí,"40.42783, -3.68459"
30,270010775,39,Felgosas-A Coruña,ReinaldoReini,False,-8.285718,43.315855,No,"43.31585514, -8.2857176"
31,184537316,408,PARAGUAY,miguelx94,False,-8.176534,43.496028,No,"43.4960276, -8.17653443"
32,1580184631,102,Elche.,josevcanales,False,-0.643128,38.219706,No,"38.21970556, -0.64312778"
33,719905537396228096,706,"Mijas, Spain",AlanDreezer,False,-4.673660,36.555811,No,"36.55581127, -4.67365971"
34,1495328876,763,"Madrid, Comunidad de Madrid",Pablocarroglez,False,-3.746949,40.322687,No,"40.322687, -3.746949"
35,246837853,2480,Madrid,Kutxi_Pacheco,False,-3.700420,40.440970,Sí,"40.44097, -3.70042"
36,142451580,52,Madrid,murcianicaguapa,False,-8.782765,42.264213,No,"42.26421295, -8.78276507"
37,709714971,872,"Málaga, España",MarPadilla_,False,-4.461353,36.666172,No,"36.66617241, -4.46135258"
38,15703541,5084,"Washington, D.C.",wbdnewton,False,-3.707360,40.421380,Sí,"40.42138, -3.70736"
39,1553476147,214,Madrid - Spain,MuchoFunkSpain,False,-3.457420,40.446570,No,"40.44657, -3.45742"
40,849681349162283008,217,"Principado de Asturias, España",sparacingfoto,False,-3.686452,43.388387,No,"43.38838729, -3.68645155"
41,757471410,324,"Glasgow, Scotland",20_Tina_Torres,False,-3.711527,40.422560,No,"40.42256044, -3.71152739"
42,1122025458,846,"A Coruña, España",acasar51,False,-8.264650,43.322800,No,"43.3228, -8.26465"
43,233345061,2437,Albacete,A_MtnezIniesta,False,-3.692180,40.419010,Sí,"40.41901, -3.69218"
44,1723462104,103,"Torrent, Valencia",adolvale,False,-0.466667,39.433300,No,"39.4333, -0.466667"
45,84143687,1814,Madrid - Cáceres,Alpaniagu,False,-3.703260,40.464447,Sí,"40.46444702, -3.70326036"
46,106841104,90,Cuidotumascota.com,OLKI69,False,-3.584300,40.360320,No,"40.36032, -3.5843"
47,943230391,64,Arteixo,chelodxastre,False,-8.401650,43.369760,No,"43.36976, -8.40165"
48,1337479172441169920,1328,"Sevilla, España",CajonSevillano,False,-5.990828,37.389712,Sí,"37.389712, -5.9908279"
49,446433608,924,Villalba Sity,SandraAyuso_,False,-3.985473,40.644887,No,"40.6448867, -3.98547318"
50,490529286,431,JLAM ∞,likeblueskies,False,-3.656678,40.520858,No,"40.52085767, -3.65667848"
51,3352643962,256,"Valencia, España",alexvelasco943,False,0.050000,38.650000,No,"38.65, 0.05"
52,799512942,1149,"Las Palmas, Islas Canarias",BombonKarol,False,-17.980833,27.641944,Sí,"27.64194444, -17.98083333"

Una curiosidad final: vamos a mostrar  dónde está cada usuario (si esto no funciona no pasa nada es solo ilustrativo)

In [28]:
import folium

m = folium.Map(zoom_start=5,location=[37,-10])
for i,fila in df_coord.iterrows():
    # añadir marcador al mapa
    marcador = folium.Marker(location=[fila["lat"], fila["long"]], popup=fila["screen_name"] )
    marcador.add_to(m)
   
# mostramos el mapa
m