
## Adquisición y preprocesamiento de la información

<table>
    <tr>
      <td>Grado en Ingeniería de Datos e Inteligencia Artificial - Facultad de Informática - UCM
      </td>
      <td>
      <img src="https://www.libreriadelprado.com/3720-large_default/la-mejor-cocinera-recetas-de-cocina.jpg"  width=150/>
      </td>
     </tr>
</table>



### Práctica 10 -Solución

### Carga de bibliotecas y modelos de spaCy

In [1]:
modules = ["bs4", "spacy", "pandas","seaborn","scipy"]

import sys
import os.path
from subprocess import check_call
import importlib
import os

def instala(modules):
  print("Instalando módulos")
  for m in modules:
      # para el import quitamos [...] y ==...
      p = m.find("[")
      mi = m if p==-1 else m[:p]
      p = mi.find("==")
      mi = mi if p==-1 else mi[:p]

      torch_loader = importlib.util.find_spec(mi)
      if torch_loader is not None:
          print(m," encontrado")
      else:
          print(m," No encontrado, instalando...",end="")  
          try:        
            r = check_call([sys.executable, "-m", "pip", "install", "--user", m])
            print("¡hecho!")
          except:
            print("¡Problema al instalar ",m,"! ¿seguro que el módulo existe?",sep="")
              
  print("¡Terminado!")

instala(modules)

Instalando módulos
bs4  encontrado
spacy  encontrado
pandas  encontrado
seaborn  encontrado
scipy  encontrado
¡Terminado!

In [2]:
# ahora el modelo para español; ojo esto puede tardar y solo debe hacerse una vez, comentarlo tras la primera ejecución
!python -m spacy download es_core_news_md

In [85]:
# cargamos el modelo
import es_core_news_md

nlp = es_core_news_md.load()

stops= ["gramo", "gramos","kilo","kilos","litro", "litros","punto","hora","horas","minuto","minutos","fuego",
        "fuente","cacerola","horno",
       "cucharada","cucharadas","trozo","trozos","molde","moldes"]
[nlp.Defaults.stop_words.add(w) for w in stops]
print("Listo!")

Listo!

**Ejercicio 1** Cargar el texto de la página:

https://www.gutenberg.org/cache/epub/8870/pg8870.html  mediante requests (para obtener) y BeautifulSoup (para analizar y extraer el texto) dejándolo en una variable de nombre `texto`. Asegurarse de que requests no da error, mostrando un mensaje si el `status_code` es distinto de 200

In [86]:
from bs4 import BeautifulSoup
import requests
pagina = "https://www.gutenberg.org/cache/epub/8870/pg8870.html"

page = requests.get(pagina)
if page.status_code==200:
    soup = BeautifulSoup(page.text, 'html.parser')  # le pasamos el texto en HTML para que lo analice
    texto = soup.text
else:
    print("Error ", page.status_code)

**Ejercicio 2** Aplicar el modelo `nlp`al `texto` dejando el resultado en una variable `doc`.
A partir de `doc` extraer una lista de todos los lexemas en mayúsculas de los tokens que 

1) Sean valores alfauméricos
2) No correspondan a palabras vacías
3) Sean sustantivos

El resultado será una lista de palabras en mayúscula (lexemas) que guardaremos en una variable `palabras`

Ayuda: un token es un sustantivo si `token.pos_ == "NOUN"`. La palabra *pos* viene de *part of speech* e indica el tipo de palabra que es. Ver la [ayuda de spaCy](https://spacy.io/usage/linguistic-features) para un ejemplo

In [87]:
doc = nlp(texto)
palabras = [p.lemma_.upper() for p in doc
            if p.is_alpha and not p.is_stop and p.pos_=="NOUN"]
palabras

['PART',
 'EBOOK',
 'RECENTLY',
 'UPDATED',
 'RECETA',
 'RECETA',
 'COCINA',
 'ÍNDICE',
 'CALDO',
 'AVE',
 'LEGUMBR',
 'VERDURA',
 'CEREAL',
 'YEMA',
 'OBISPO',
 'HUEVO',
 'CROQUETA',
 'AJO',
 'PASTA',
 'MACARRONES',
 'ALMEJA',
 'PESCADO',
 'QUESO',
 'MARISCO',
 'ALMENDRA',
 'ARROZ',
 'PESCADO',
 'VIGILIA',
 'VIGILIA',
 'ALMEJA',
 'CARNE',
 'AVE',
 'OSTRA',
 'PURÉ',
 'JUDÍA',
 'HUEVO',
 'ARAGONESA',
 'GARBANZO',
 'GUISANT',
 'LENTEJA',
 'JUDÍA',
 'PATATA',
 'ESPINACA',
 'HABA',
 'PATATA',
 'GRATÍN',
 'JUDÍA',
 'ESTOFADA',
 'CHORIZO',
 'GARBANZO',
 'ESPINACA',
 'POTAJE',
 'GARBANZO',
 'LENTEJA',
 'LENTEJA',
 'HABA',
 'GUISANT',
 'ALUBIA',
 'VELOUTÉ',
 'JUDÍA',
 'ESTOFADA',
 'VERDURAS',
 'ALCACHOFAS',
 'HABA',
 'ZANAHORIA',
 'PASTEL',
 'COLIFLOR',
 'SALSA',
 'HABA',
 'HABA',
 'MAÎTRE',
 'BILBAÍNA',
 'PARISIÉN',
 'GUISANT',
 'CREMA',
 'ALCACHOFAS',
 'FRITAS',
 'ACEDERAS',
 'HUEVO',
 'MEZCLA',
 'VERDURA',
 'SETAS',
 'ESPINACA',
 'SALSA',
 'PURÉ',
 'PASTEL',
 'CARNE',
 'SALCHICHA',
 'MAÎTRE',
 'PATATA',
 'VINAGRETA',
 'SOUFFLÉS',
 'ACELGA',
 'PAQUETITO',
 'FRITAS',
 'ENSALADAS',
 'ESCAROLA',
 'PEPINO',
 'REMOLACHA',
 'APIO',
 'ENSALADA',
 'PUNTA',
 'ESPÁRRAGO',
 'ENSALADA',
 'ALCACHOFAS',
 'PATATA',
 'ANCHOAS',
 'CARDO',
 'VINAGRETA',
 'ALMENDRA',
 'YEMA',
 'MAÎTRE',
 'TOMATE',
 'TRUFAS',
 'CREMA',
 'AVE',
 'CARNE',
 'CERDO',
 'LANGOSTINO',
 'CANGREJO',
 'CHAUFROIX',
 'HIERBA',
 'HUEVO',
 'AGUA',
 'HUEVO',
 'CAMISA',
 'CRISTAL',
 'PALACIO',
 'CAPRICHO',
 'TURCA',
 'POLINAC',
 'QUESO',
 'PRIMAVERA',
 'HUEVO',
 'FÓRMULA',
 'HUEVO',
 'GUISANT',
 'ESPÁRRAGO',
 'TOMATE',
 'MANTEQUILLA',
 'SALCHICHA',
 'JAMÓN',
 'CUBILETE',
 'PLATO',
 'MARINERA',
 'QUESO',
 'MONSTRUO',
 'TORTILLA',
 'PATATA',
 'ESPÁRRAGO',
 'ALCACHOFAS',
 'GUISANT',
 'QUESO',
 'LECHE',
 'BACALAO',
 'PICADILLO',
 'SESO',
 'ANCHOAS',
 'MERLUZA',
 'CHORIZO',
 'BECHAMELLE',
 'RON',
 'HIERBA',
 'FÓRMULA',
 'FÓRMULA',
 'SALSA',
 'FÓRMULA',
 'VINAGRETA',
 'MARINERA',
 'MAYONESA',
 'SALSA',
 'MERLUZA',
 'PASTEL',
 'MERLUZA',
 'MERLUZA',
 'FLORENTINA',
 'SALSA',
 'VIZCAÍNA',
 'AJO',
 'CROQUETAS',
 'ACEITUNA',
 'FRITO',
 'CHAMBORD',
 'GENOVESA',
 'ALCAPARRA',
 'PLATO',
 'TOMATE',
 'FÓRMULA',
 'MARINERA',
 'SALSA',
 'ALMEJA',
 'SALSA',
 'JAMÓN',
 'CHIPIRÓN',
 'TINTA',
 'RELLENO',
 'LUBINA',
 'CALDO',
 'LENGUADO',
 'ALMEJA',
 'PLATO',
 'GRATÍN',
 'RUSA',
 'TOMATE',
 'RELLENA',
 'FRITA',
 'ASADA',
 'PARRILLA',
 'GRATÍN',
 'FRITA',
 'LIMÓN',
 'CHAMBORD',
 'PARRILLA',
 'RELLENA',
 'ALEMANA',
 'HUEVO',
 'RANA',
 'FÓRMULA',
 'SALSA',
 'FRITA',
 'ASADA',
 'GUISADA',
 'TOMATE',
 'GUISANT',
 'TOMATE',
 'TOMATE',
 'RELLENOS',
 'CONCHA',
 'PIMIENTO',
 'RELLENO',
 'HUEVO',
 'ALCACHOFAS',
 'RELLENA',
 'CERDO',
 'RELLENO',
 'NAVARRA',
 'CONSERVAS',
 'RECETA',
 'PASTA',
 'SALMUERA',
 'PIMIENTO',
 'HABA',
 'VAINA',
 'ESPÁRRAGOS',
 'MELOCOTÓN',
 'VINAGRE',
 'CARNES',
 'CARNE',
 'ALCACHOFAS',
 'CHULETA',
 'ASADA',
 'GORRINITO',
 'RAJAS',
 'ALCACHOFAS',
 'FIAMBRE',
 'FÓRMULA',
 'BECHAMELLE',
 'JARDINERA',
 'CARNE',
 'ACEITUNA',
 'ZANAHORIA',
 'TORO',
 'TORO',
 'PATATA',
 'ALEMANA',
 'ITALIANA',
 'FILETES',
 'CARNERO',
 'PRIMAVERA',
 'RUSA',
 'ASADOR',
 'CARNERO',
 'PATATA',
 'PECHO',
 'CARNERO',
 'CARNERO',
 'VERDURA',
 'CHAMPIÑONS',
 'PICATOST',
 'SETA',
 'PAPILLOT',
 'ESCARLATA',
 'CARNERO',
 'SALSA',
 'CHULETA',
 'ASADA',
 'TOMATE',
 'JUGO',
 'PECHO',
 'CARNERO',
 'CARNERO',
 'CAMPESINA',
 'CARNERO',
 'PARRILLA',
 'CORDERO',
 'PAPILLOTE',
 'CORDERO',
 'EMPANADA',
 'CORDERO',
 'BECHAMELLE',
 'CARNERO',
 'TOMATE',
 'CARNERO',
 'SALSA',
 'CLASE',
 'CARNE',
 'CARNES',
 'GUISADAS',
 'TOMATE',
 'PIMIENTO',
 'CEBOLLA',
 'BECHAMELLE',
 'ARROZ',
 'CERDO',
 'MANO',
 'SALSA',
 'BECHAMELLE',
 'MANO',
 'PASTEL',
 'HÍGADO',
 'HÍGADO',
 'TOMATE',
 'GUISANT',
 'BECHAMELLE',
 'ITALIANA',
 'DULCE',
 'MOMENTO',
 'DULCE',
 'HUEVO',
 'FÓRMULA',
 'QUESO',
 'CABEZA',
 'CERDO',
 'CRUDO',
 'MORCILLA',
 'SALMUERA',
 'EMBUTIDO',
 'FRITO',
 'FRITO',
 'HUECO',
 'FRITO',
 'PATATA',
 'PATATA',
 'VIENTO',
 'BACALAO',
 'FÓRMULA',
 'PECHUGA',
 'FRITAS',
 'TOMATE',
 'SALSA',
 'MARINERA',
 'FRITO',
 'ARROZ',
 'ZANAHORIA',
 'GUISANT',
 'MANCHEGA',
 'POLLO',
 'PEPITORIA',
 'FÓRMULA',
 'GALLINA',
 'CAPÓN',
 'TRUFAS',
 'PEBRE',
 'ACEITUNA',
 'RELLENO',
 'ACEITUNA',
 'PAVO',
 'CHAMPIÑÓN',
 'SALSA',
 'FÓRMULA',
 'HOJA',
 'PARRA',
 'TOMATE',
 'SALSA',
 'PERDICES',
 'RELLENA',
 'ESTOFADA',
 'FÓRMULA',
 'FÓRMULA',
 'PERDICES',
 'MALVIZ',
 'SALSA',
 'GUISADA',
 'PAPILLOTES',
 'PASTEL',
 'LIEBRE',
 'SALSA',
 'FÓRMULA',
 'PEPITORIA',
 'PIERNA',
 'FÓRMULA',
 'ASADA',
 'MONTE',
 'PASTEL',
 'AVE',
 'AVE',
 'ARROZ',
 'PICADILLO',
 'JAMÓN',
 'MENUDILLO',
 'SALCHICHA',
 'POLLO',
 'RIOJANA',
 'ARROZ',
 'LANGOSTA',
 'ALMEJA',
 'ARROZ',
 'RIÑÓN',
 'VIGILIA',
 'ARROZ',
 'GUISANT',
 'PLATOS',
 'TOMATE',
 'LECHE',
 'PATATA',
 'MIGAS',
 'GUISADA',
 'HOJALDRE',
 'HOJALDRE',
 'HOJALDRE',
 'EMPANADILLA',
 'PAN',
 'EMPANADILLA',
 'LECHE',
 'EMPANADILLA',
 'CALDO',
 'PATATA',
 'CARNERO',
 'CALDO',
 'CARNERO',
 'CERDO',
 'TERNERA',
 'CROQUETA',
 'BRAZO',
 'GITANO',
 'FÓRMULA',
 'ALMÍBAR',
 'MANTECA',
 'CANELA',
 'GITANO',
 'ALMENDRA',
 'CHOCOLATE',
 'ESPUMA',
 'RELLENO',
 'FRUTA',
 'PASTEL',
 'ARROZ',
 'FRUTA',
 'PATATA',
 'CHOCOLATE',
 'MANZANA',
 'CASTAÑA',
 'RON',
 'TÉ',
 'TÉ',
 'CAPUCHINA',
 'ROSQUILLA',
 'FRITA',
 'CONSEJO',
 'MANTECADO',
 'ALMENDRA',
 'MERENGUE',
 'ROSCA',
 'ALMENDRA',
 'CHATCHIGORRIS',
 'LIMÓN',
 'LECHE',
 'BAÑO',
 'LECHE',
 'PLÁTANO',
 'ARROZ',
 'LECHE',
 'CROQUETA',
 'ARROZ',
 'POSTRE',
 'LECHE',
 'CAÑA',
 'CHOCOLATE',
 'CREMA',
 'PASTEL',
 'POSTRE',
 'MANZANA',
 'ALMENDRA',
 'NARANJA',
 'CREMA',
 'MANZANA',
 'CIELO',
 'NARANJA',
 'LIMÓN',
 'AVELLANA',
 'ALMENDRA',
 'BIZCOCHO',
 'CAFÉ',
 'CHOCOLATE',
 'TÉ',
 'MANTEQUILLA',
 'LECHE',
 'HOJA',
 'NONO',
 'HUEVO',
 'ROSCÓN',
 'CAFÉ',
 'AVELLANA',
 'FRUTA',
 'PASTEL',
 'PASTELILLO',
 'MANZANA',
 'MANZANA',
 'GLACÉ',
 'AZÚCAR',
 'FRUTA',
 'YEMA',
 'BAÑO',
 'CAPUCHINA',
 'COCO',
 'PASTILLA',
 'CAFÉ',
 'HUEVO',
 'BIZCOCHO',
 'HUEVO',
 'ALMENDRA',
 'FRUTAS',
 'MEMBRILLO',
 'MEMBRILLO',
 'MANZANA',
 'MANZANA',
 'MANZANA',
 'MANZANA',
 'MANZANA',
 'MANZANA',
 'NARANJA',
 'NARANJA',
 'NARANJA',
 'LIMÓN',
 'CEREZA',
 'GUINDA',
 'GUINDA',
 'CIRUELA',
 'CLAUDIA',
 'HIGO',
 'PASTA',
 'CIRUELA',
 'HIGO',
 'MELOCOTÓN',
 'ALBARICOQUE',
 'PERA',
 'PERA',
 'PERA',
 'MANZANA',
 'MELOCOTÓN',
 'SANDÍA',
 'SANDÍA',
 'FRESA',
 'FRESA',
 'FRESA',
 'GROSELLA',
 'GROSELLA',
 'BATATA',
 'BATATA',
 'UVA',
 'UVA',
 'CIRUELA',
 'HIGO',
 'UVA',
 'QUESO',
 'HELADO',
 'FRESA',
 'ARLEQUÍN',
 'LIMÓN',
 'LECHE',
 'CANELA',
 'VAINILLA',
 'GROSELLA',
 'NARANJA',
 'HELADO',
 'CAFÉ',
 'CAFÉ',
 'LECHE',
 'AVELLANA',
 'FRUTA',
 'HELADO',
 'ALMENDRA',
 'COCO',
 'CHOCOLATE',
 'BIZCOCHO',
 'HELADO',
 'HUEVO',
 'COCO',
 'PONCHE',
 'MALVAVISCO',
 'GROSELLA',
 'CAFÉ',
 'HUEVO',
 'GUINDA',
 'MENTA',
 'NARANJA',
 'FRESA',
 'FÓRMULA',
 'SERVIR',
 'COMIDA',
 'MENÚ',
 'ALMUERZO',
 'MENÚ',
 'COMIDA',
 'MENÚ',
 'BANQUETES',
 'RECETA',
 'TOCADOR',
 'AGUA',
 'COLONIA',
 'CABEZA',
 'OBJETO',
 'TOCADOR',
 'DIENTE',
 'FÓRMULA',
 'POLVO',
 'OJO',
 'PÁRPADO',
 'MANO',
 'ARRUGA',
 'PÁRPADO',
 'COLOR',
 'CARA',
 'ROSTRO',
 'UÑA',
 'RECETA',
 'LIMPIEZA',
 'SEBO',
 'ACEITE',
 'FRÍO',
 'PASTA',
 'BRILLO',
 'SUELO',
 'CALZADO',
 'COLOR',
 'FÓRMULA',
 'PLATA',
 'BRONCE',
 'MÁRMOL',
 'MANCHA',
 'ACEITE',
 'CUERO',
 'OBJETO',
 'HIERRO',
 'MUEBLE',
 'FRANELA',
 'FÓRMULA',
 'ACERO',
 'MANCHA',
 'TINTA',
 'CERA',
 'ESPERMA',
 'CAMA',
 'DUEÑA',
 'HOGAR',
 'LIBRO',
 'COCINA',
 'COCINERA',
 'CASA',
 'SEÑORA',
 'POSICIÓN',
 'ORDEN',
 'ECONOMÍA',
 'LIBRO',
 'CASA',
 'POBLACIÓN',
 'COMERCIO',
 'AMA',
 'CASA',
 'TIEMPO',
 'CLASE',
 'CONSERVA',
 'VERDURA',
 'FRUTA',
 'PESCADO',
 'CARNE',
 'LIBRO',
 'FORMA',
 'DESPENSA',
 'DUEÑA',
 'PREPARACIÓN',
 'COMIDA',
 'MENÚ',
 'LIBRO',
 'RECETA',
 'INVITADO',
 'FAMILIAR',
 'ENTREMÉS',
 'LICOR',
 'LIBRO',
 'PREMIO',
 'COLEGIO',
 'ESCUELA',
 'NIÑA',
 'SEGURIDAD',
 'REGALO',
 'RECETA',
 'COCINA',
 'REGIÓN',
 'CLASE',
 'POSTRE',
 'REPOSTERÍA',
 'PASTELERÍA',
 'HELADO',
 'LICOR',
 'RESULTADO',
 'SEÑORA',
 'CLASE',
 'FÓRMULA',
 'LIMPIEZA',
 'LEJÍA',
 'JABÓN',
 'PREMIO',
 'LIBRO',
 'SEÑORITA',
 'ESCUELA',
 'COLEGIO',
 'EJEMPLAR',
 'VÍAS',
 'FAMILIA',
 'DISPENDIO',
 'COMIDA',
 'AGRADO',
 'MADRE',
 'ESCUELA',
 'NIÑA',
 'SEMANA',
 'PRÁCTICA',
 'COCINA',
 'COLEGIO',
 'GASTO',
 'MATERIAL',
 'NIÑA',
 'MUJER',
 'SOLIDEZ',
 'BASE',
 'EDIFICIO',
 'SOCIEDAD',
 'TRANSCENDENCIA',
 'VIDA',
 'FAMILIA',
 'CALDO',
 'CALDO',
 'CARNE',
 'BUEY',
 'AGUA',
 'SAL',
 'ZANAHORIA',
 'PUERRO',
 'CALDO',
 'JAMÓN',
 'JÍCARA',
 'GARBANZO',
 'CHORIZO',
 'CALDO',
 'AVE',
 'AGUA',
 'SAL',
 'PUERRO',
 'CEBOLLETA',
 'RAMITA',
 'PEREJIL',
 'ESPUMA',
 'CALDO',
 'EXTRACTO',
 'CARNE',
 'GELATINA',
 'AVE',
 'AGUA',
 'CALDO',
 'AGUA',
 'JÍCARA',
 'LENTEJA',
 'HABICHUELA',
 'ALUBIA',
 'ZANAHORIA',
 'PUERRO',
 'CEBOLLETA',
 'PEREJIL',
 'COLIFLOR',
 'SAL',
 'ACEITE',
 'CALDO',
 'TAMIZ',
 'NIÑO',
 'CONVALECIENT',
 'CALDO',
 'AGUA',
 'JÍCARA',
 'CEBADA',
 'TRIGO',
 'AVENA',
 'MAÍZ',
 'CENTENO',
 'SAL',
 'PÁSENLO',
 'COLADOR',
 'BATIDA',
 'YEMA',
 'PLATO',
 'TROCITO',
 'CUADRADITOS',
 'CALDO',
 'CUADRADITO',
 'JAMÓN',
 'SOPA',
 'MANTEQUILLA',
 'HARINA',
 'CALDO',
 'YEMA',
 'HUEVO',
 'RATITO',
 'NIEVE',
 'FRITO',
 'PORCIÓN',
 'SOPA',
 'MANTECA',
 'PUERROS',
 'CEBOLLA',
 'PATATA',
 'NABO',
 'ZANAHORIA',
 'TIRITA',
 'HOJITA',
 'HIERBABUENA',
 'PEREJIL',
 'REPOLLO',
 'TROCITO',
 'SAZONA',
 'SAL',
 'CALDO',
 'SOPA',
 'SOPA',
 'MANTECA',
 'VIGILIA',
 'ACEITE',
 'CALDO',
 'SAL',
 'AVELLANA',
 'HUEVO',
 'PERSONA',
 'HUEVO',
 'TAZA',
 'HARINA',
 'LECHE',
 'YEMA',
 'HUEVO',
 'MASA',
 'NIEVE',
 'ACEITE',
 'CALDO',
 'SOPA',
 'PASTA',
 'CROQUETA',
 'BOLITA',
 'TAMAÑO',
 'GARBANZO',
 'MIGA',
 'PAN',
 'HUEVO',
 'CALDO',
 'TIEMPO',
 'LUGAR',
 'CROQUETA',
 'CALDO',
 'MENUDILLO',
 'AVE',
 'PEDACITO',
 'SOPA',
 'SOPA',
 'PAN',
 'TARTERA',
 'PAN',
 'ACEITE',
 'FRITO',
 'AJO',
 'AGUA',
 'SAL',
 'TARTERA',
 'SOPA',
 'CALDO',
 'ONZAS',
 'PASTA',
 'SOPA',
 'RATO',
 'CALDO',
 'MACARRÓN',
 'QUESO',
 'RATITO',
 'SOPA',
 'AGUA',
 'SAL',
 'CONCHA',
 'ALMEJA',
 'CAZUELA',
 'FRITO',
 'AJO',
 'CEBOLLETA',
 'TOMATE',
 'PEREJIL',
 'COLADOR',
 'AGUA',
 'ALMEJA',
 'ARROZ',
 'REBANADITAS',
 'PAN',
 'SOPA',
 'PESCADO',
 'LIBRA',
 'PESCADO',
 'AGUA',
 'PLATO',
 'SOPA',
 'PESCADO',
 'HARINA',
 'FRÍE',
 'ACEITE',
 'ACEITE',
 'TOMATE',
 'AJO',
 'CEBOLLA',
 'PIMIENTO',
 'PEREJIL',
 'PAN',
 'SALSA',
 'ALMENDRA',
 'AVELLANA',
 'TOSTADA',
 'PESCADO',
 'AGUA',
 'SAL',
 'MAYONESA',
 'YEMA',
 'HUEVO',
 'PLATO',
 'SOPA',
 'CALDO',
 'PESCADO',
 'COLADOR',
 'MAYONESA',
 'REBANADITA',
 'PAN',
 'SOPA',
 'MANTECA',
 'VACA',
 'CEBOLLA',
 'CEBOLLA',
 'AGUA',
 'SOPA',
 'SAL',
 'TARTERA',
 'CAPA',
 'REBANADA',
 'PAN',
 'CAPA',
 'QUESO',
 'PAN',
 'CALDO',
 'RATO',
 'SOPA',
 'ACEITE',
 'AJO',
 'CEBOLLA',
 'TOMATE',
 'MARISCO',
 'AGUA',
 'CONCHA',
 'REBANADITA',
 'PAN',
 'SOPA',
 'PATATA',
 'BECHAMELLE',
 'JAMÓN',
 'PATATA',
 'PASTA',
 'CUCHARA',
 'MADERA',
 'PASTA',
 'YEMA',
 'PATATA',
 'CALDO',
 'PASTA',
 'BOLITA',
 'SOPA',
 'SOPA',
 'ALMENDRA',
 'AGUA',
 'ACEITE',
 'AJO',
 'REBANADA',
 'PAN',
 'COSA',
 'MORTERO',
 'AGUA',
 'SAL',
 'SOPA',
 'MEZCLA',
 'MORTERO',
 'SOPA',
 'ARROZ',
 ...]

**Ejercicio 3** Quedarse solo con las `N` palabras más frecuentes en `palabras`. El resultado sera una lista `frecuentes`.

El resultado esperado para `frecuentes`es ['AGUA', 'HUEVO', 'SAL', 'MANTECA',...]

In [88]:
from collections import Counter
N=25

c = Counter(palabras)
frecuentes = [p for p,_ in c.most_common(N)]
frecuentes

['AGUA',
 'HUEVO',
 'SAL',
 'MANTECA',
 'AZÚCAR',
 'SALSA',
 'ACEITE',
 'HARINA',
 'CALDO',
 'PEREJIL',
 'YEMA',
 'PASTA',
 'PAN',
 'AJO',
 'VINO',
 'JAMÓN',
 'LIMÓN',
 'TOMATE',
 'LECHE',
 'CEBOLLA',
 'MANTEQUILLA',
 'CARNE',
 'CERDO',
 'ALMÍBAR',
 'VACA']

**Ejercicio 4** A partir de `doc` obtener una lista `frases`con todas las oraciones del libro en mayúsculas. El resultado esperado será de la forma:

        ['\n',
         'THE PROJECT GUTENBERG EBOOK OF LA MEJOR COCINERA, RECETAS DE COCINA, BY CALLEJA\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTHE PROJECT GUTENBERG EBOOK OF LA MEJOR COCINERA...]

Ayuda: recordar que .text devuelve el texto asociado, ya sea a una palabra, una oración, etc.

In [89]:
frases = [o.text.upper() for o in doc.sents]

# para probar
frases[:2]

['\n',
 'THE PROJECT GUTENBERG EBOOK OF LA MEJOR COCINERA, RECETAS DE COCINA, BY CALLEJA\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTHE PROJECT GUTENBERG EBOOK OF LA MEJOR COCINERA, RECETAS DE COCINA\n\r\nTHIS EBOOK IS FOR THE USE OF ANYONE ANYWHERE IN THE UNITED STATES AND MOST OTHER PARTS OF THE WORLD AT NO COST AND WITH ALMOST NO RESTRICTIONS WHATSOEVER.']

**Ejercicio 5** Escribir una función:

Nombre `palabrasEnFrase`

Parámetros:

    palabras: una lista de strings representando palabras
    frase: un string representando una frase
   
Salida: una lista de 0s y 1s, con la misma longitud que `palabras` tal que en la posición i tendrá un 1 si la palabra iésima aparece en la frase y 0 en otro caso


Ayuda: `hola in 'me dijo hola'` devuelve `True`, y `hola in 'se lo llevó la ola'` devuelve `False`

In [90]:
def palabrasEnFrase(palabras,frase):
    # solución
    return [ 0 if p not in frase else 1 for p in palabras]

# salida esperada: [1, 0, 1, 0, 1, 0]
palabrasEnFrase(["PRINCESA","RAMA", "RANA", "PRINCIPE","POZO", "GOZO"],
                "HABÍA UNA VEZ UNA LINDA RANA QUE AL CAERSE A UN POZO SE CONVIRTIÓ EN UNA HORRIBLE PRINCESA")

[1, 0, 1, 0, 1, 0]

**Ejercicio 6** A partir de `frecuentes`(ejercicio 3) y `frases` (ejercicio 4) queremos obtener una lista `pertenencia`donde 

1) `pertenencia` tiene tantos elementos como `frases` (uno por frase)
2) El elemento i-ésimo de `pertenencia` es una lista de  1s y 0s con la misma longitud que `frecuentes` indicando si cada palabra de `frecuentes` está en la frase i-ésima.

Con otras palabras pertenencia es una lista de listas donde `pertenencia[i][j] == 1` si `frecuentes[j]` aparece en `frases[i]`, y 0 en otro caso

Nota: conviene usar la función del ejercicio 5

In [91]:
pertenencia = [palabrasEnFrase(frecuentes,f) for f in frases]
pertenencia

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
 [1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
 [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],

In [92]:
# para probar; 
import pandas as pd
df = pd.DataFrame(pertenencia,columns=frecuentes)
df

,AGUA,HUEVO,SAL,MANTECA,AZÚCAR,SALSA,ACEITE,HARINA,CALDO,PEREJIL,...,JAMÓN,LIMÓN,TOMATE,LECHE,CEBOLLA,MANTEQUILLA,CARNE,CERDO,ALMÍBAR,VACA
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,1,1,1,1,0,1,0,...,1,1,1,1,1,1,1,1,1,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1588,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

El siguiente código elimina aquellas filas que no tienen ninguna de las palabras más frecuentes

In [93]:
df2 = df[df!=0].dropna(how="all").fillna(0).reset_index(drop=True)
df2

,AGUA,HUEVO,SAL,MANTECA,AZÚCAR,SALSA,ACEITE,HARINA,CALDO,PEREJIL,...,JAMÓN,LIMÓN,TOMATE,LECHE,CEBOLLA,MANTEQUILLA,CARNE,CERDO,ALMÍBAR,VACA
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1173,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1174,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1175,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1176,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**Ejercicio 7** Mostrar las parejas de columnas diferentes en `df2`que tengan una correlación superior a 0.25

Nota 1: En este ejercicio sí se puede (incluso se anima a) usar bucles `for` fuera de listas intensionales

Nota 2: evitar que salgan parejas de columnas repetidas o una columna consigo misma

Ayuda: Si llamamos correlaciones al dataframe generado por corr, podemos acceder a la correlación de la columna c1 con la c2 (con c1,c2 nombres de columnas de df2) mediante `correlaciones.loc[c1,c2]`

In [94]:
correlaciones = df2.corr()
for c1 in df2.columns:
    for c2 in df2.columns:
        if c1<c2:
            v = correlaciones.loc[c1,c2]
            if abs(v)>0.20:
                print(c1,c2,v)

HUEVO YEMA 0.38812906606593217
HUEVO LECHE 0.20064279827638876
SAL SALSA 0.48415544774965974
MANTECA VACA 0.39694701261037896
AZÚCAR SAL -0.3071520827914276
AZÚCAR YEMA 0.25916947681582814
SALSA TOMATE 0.2171688422453101
ACEITE AJO 0.24086566820240882
ACEITE CEBOLLA 0.21622425946029317
HARINA HUEVO 0.205314104584959
HARINA MANTECA 0.21070111719376788
CALDO CEBOLLA 0.25218969837380106
AJO PEREJIL 0.3466567380124757
AJO CEBOLLA 0.2646692737858073
LECHE YEMA 0.23677963868386767
CEBOLLA PEREJIL 0.35454465517233247
CEBOLLA TOMATE 0.24844140978191234
CERDO MANTECA 0.21381447982144924
ALMÍBAR AZÚCAR 0.20708252025695587

¿Qué dos ingredientes parece más improbable encontrar juntos a la vista de estas correlaciones?

**Ejercicio 8** Las matrices de 0 y 1s se pueden considerar por un lado tipo ratio y por otro lado nominales. Vamos a considerar ahora que todas las columnas son nominales y en lugar de calcular las correlaciones numéricas vamos a utilizar las asociaciones entre variables nominales. 

Es decir, ahora para cada par de columnas tendremos que calcular su tabla de contingencias y el test $\mathcal{X}^2$. Lo único que vamos a ser muy exigentes: solo descartamos la hipóstesis nula y consideramos que hay una posible relación cuando `p< 10e-8`. Mostrar las parejas distintas que verifican que hay relación entre ellas con estas condiciones 

Nota: evitar que salgan parejas de columnas repetidas o una columna consigo misma

Comentario general: saldrán muy parecidas al ejercicio anterior pero con alguna nueva. LA desventaja es que no vemos si es asociación positiva o negativa, por lo que se suele preferir el método anterior en el caso de variables "dummy". En el caso de variables nominales es muy habitual la secuencia:
1) Buscar asociaciones con  $\mathcal{X}^2$ entre variables nominales
2) Convertir a variables dummy con one-hot-encoding
3) Repetir las correlaciones, ahora ya como variables numéricas con `corr()`que nos mostrará posibles correlaciones con otras variables ratio y entre sí, pero ahora entre valores individuales de la varaible nominal

In [107]:
from scipy.stats import chi2_contingency
for c1 in df2.columns: 
    for c2 in df2.columns:
         if c1<c2:
            contingencias=pd.crosstab(index=df2[c1],columns=df2[c2])
            ChiSqResult = chi2_contingency(contingencias)
            p = ChiSqResult[1]
            if p<10e-8:
                print(c1,c2)

HUEVO YEMA Chi2ContingencyResult(statistic=174.46886385552125, pvalue=7.81977286445713e-40, dof=1, expected_freq=array([[782.80373832,  97.19626168],
       [264.19626168,  32.80373832]]))
HUEVO LECHE Chi2ContingencyResult(statistic=45.61533826048226, pvalue=1.4391025170935927e-11, dof=1, expected_freq=array([[816.44859813,  63.55140187],
       [275.55140187,  21.44859813]]))
HUEVO MANTEQUILLA Chi2ContingencyResult(statistic=29.66918703403079, pvalue=5.124290210114199e-08, dof=1, expected_freq=array([[822.42990654,  57.57009346],
       [277.57009346,  19.42990654]]))
SAL SALSA Chi2ContingencyResult(statistic=273.19706619714395, pvalue=2.2810641615520522e-61, dof=1, expected_freq=array([[561.0433305, 101.9566695],
       [434.9566695,  79.0433305]]))
SAL TOMATE Chi2ContingencyResult(statistic=35.061704079698714, pvalue=3.1942128172289826e-09, dof=1, expected_freq=array([[608.92353441,  54.07646559],
       [472.07646559,  41.92353441]]))
MANTECA VACA Chi2ContingencyResult(statistic=181.52127041898848, pvalue=2.255655735951773e-41, dof=1, expected_freq=array([[865.12149533,  58.87850467],
       [236.87850467,  16.12149533]]))
AZÚCAR SAL Chi2ContingencyResult(statistic=109.39818521137687, pvalue=1.3275104370554214e-25, dof=1, expected_freq=array([[550.34069669, 426.65930331],
       [112.65930331,  87.34069669]]))
AZÚCAR SALSA Chi2ContingencyResult(statistic=34.38715507296439, pvalue=4.516944939501879e-09, dof=1, expected_freq=array([[826.75615973, 150.24384027],
       [169.24384027,  30.75615973]]))
AZÚCAR HARINA Chi2ContingencyResult(statistic=36.15485902639943, pvalue=1.8224350283836158e-09, dof=1, expected_freq=array([[845.01784197, 131.98215803],
       [172.98215803,  27.01784197]]))
AZÚCAR PEREJIL Chi2ContingencyResult(statistic=28.814775212995713, pvalue=7.964122732116706e-08, dof=1, expected_freq=array([[859.95921835, 117.04078165],
       [176.04078165,  23.95921835]]))
AZÚCAR YEMA Chi2ContingencyResult(statistic=76.8714706622101, pvalue=1.8245384176759257e-18, dof=1, expected_freq=array([[869.09005947, 107.90994053],
       [177.90994053,  22.09005947]]))
AZÚCAR LECHE Chi2ContingencyResult(statistic=29.310983370938725, pvalue=6.164529115138922e-08, dof=1, expected_freq=array([[906.44350042,  70.55649958],
       [185.55649958,  14.44350042]]))
AZÚCAR CEBOLLA Chi2ContingencyResult(statistic=33.93958278731551, pvalue=5.685025497868703e-09, dof=1, expected_freq=array([[835.88700085, 141.11299915],
       [171.11299915,  28.88700085]]))
SALSA TOMATE Chi2ContingencyResult(statistic=53.332277212663385, pvalue=2.8164070942817524e-13, dof=1, expected_freq=array([[914.76295667,  81.23704333],
       [166.23704333,  14.76295667]]))
ACEITE AJO Chi2ContingencyResult(statistic=66.16757549303905, pvalue=4.1417005676088045e-16, dof=1, expected_freq=array([[882.00509771, 101.99490229],
       [172.99490229,  20.00509771]]))
ACEITE CEBOLLA Chi2ContingencyResult(statistic=53.37946076776703, pvalue=2.749566493146835e-13, dof=1, expected_freq=array([[841.87595582, 142.12404418],
       [165.12404418,  27.87595582]]))
HARINA HUEVO Chi2ContingencyResult(statistic=48.2418895939076, pvalue=3.767532741410248e-12, dof=1, expected_freq=array([[761.12149533, 256.87850467],
       [118.87850467,  40.12149533]]))
HARINA MANTECA Chi2ContingencyResult(statistic=50.76308967284658, pvalue=1.0421521967323308e-12, dof=1, expected_freq=array([[799.17757009, 218.82242991],
       [124.82242991,  34.17757009]]))
CALDO PEREJIL Chi2ContingencyResult(statistic=32.19556189482948, pvalue=1.3940883495401574e-08, dof=1, expected_freq=array([[916.29226848, 124.70773152],
       [119.70773152,  16.29226848]]))
CALDO VINO Chi2ContingencyResult(statistic=35.502116075009496, pvalue=2.547736437573805e-09, dof=1, expected_freq=array([[940.17247239, 100.82752761],
       [122.82752761,  13.17247239]]))
CALDO CEBOLLA Chi2ContingencyResult(statistic=72.62947908091442, pvalue=1.564249708166818e-17, dof=1, expected_freq=array([[890.64316058, 150.35683942],
       [116.35683942,  19.64316058]]))
PEREJIL SAL Chi2ContingencyResult(statistic=37.69716507031647, pvalue=8.262455159024911e-10, dof=1, expected_freq=array([[583.57519116, 452.42480884],
       [ 79.42480884,  61.57519116]]))
AJO PEREJIL Chi2ContingencyResult(statistic=137.96049377343877, pvalue=7.434114564699227e-32, dof=1, expected_freq=array([[928.61512319, 126.38487681],
       [107.38487681,  14.61512319]]))
AJO CEBOLLA Chi2ContingencyResult(statistic=79.99706320012203, pvalue=3.749666458789415e-19, dof=1, expected_freq=array([[902.62107052, 152.37892948],
       [104.37892948,  17.62107052]]))
LECHE YEMA Chi2ContingencyResult(statistic=63.101986089923784, pvalue=1.9627609822875434e-15, dof=1, expected_freq=array([[971.38827528, 120.61172472],
       [ 75.61172472,   9.38827528]]))
CEBOLLA SAL Chi2ContingencyResult(statistic=30.91928832163516, pvalue=2.6898510137732088e-08, dof=1, expected_freq=array([[567.23959218, 439.76040782],
       [ 95.76040782,  74.23959218]]))
CEBOLLA MANTECA Chi2ContingencyResult(statistic=36.5664257282508, pvalue=1.4755135159629115e-09, dof=1, expected_freq=array([[790.54205607, 216.45794393],
       [133.45794393,  36.54205607]]))
CEBOLLA PEREJIL Chi2ContingencyResult(statistic=144.8614963806649, pvalue=2.302721307881514e-33, dof=1, expected_freq=array([[886.3653356, 120.6346644],
       [149.6346644,  20.3653356]]))
CEBOLLA VINO Chi2ContingencyResult(statistic=38.16064565132852, pvalue=6.515330507943318e-10, dof=1, expected_freq=array([[909.46559048,  97.53440952],
       [153.53440952,  16.46559048]]))
CEBOLLA TOMATE Chi2ContingencyResult(statistic=70.08887786651196, pvalue=5.669171380285266e-17, dof=1, expected_freq=array([[924.86576041,  82.13423959],
       [156.13423959,  13.86576041]]))
MANTEQUILLA YEMA Chi2ContingencyResult(statistic=40.85215769020856, pvalue=1.6419187295177655e-10, dof=1, expected_freq=array([[978.5046729, 121.4953271],
       [ 68.4953271,   8.5046729]]))
CERDO MANTECA Chi2ContingencyResult(statistic=51.685516108176394, pvalue=6.514153579358099e-13, dof=1, expected_freq=array([[865.90654206, 237.09345794],
       [ 58.09345794,  15.90654206]]))
ALMÍBAR SAL Chi2ContingencyResult(statistic=39.26303913851932, pvalue=3.703866178233097e-10, dof=1, expected_freq=array([[629.76550552, 488.23449448],
       [ 33.23449448,  25.76550552]]))
ALMÍBAR AZÚCAR Chi2ContingencyResult(statistic=47.978222904761225, pvalue=4.309794973647607e-12, dof=1, expected_freq=array([[928.02548853, 189.97451147],
       [ 48.97451147,  10.02548853]]))

**Ejercicio 9** 

Nombre: `bigramas`

Parámetros: `l` , una lista de strings o palabras

Devuelve: El resultado de concatenar cada palabra con la siguiente si son distintas con un "-" entremedias

Por ejemplo, si `l=["hola","qué", "tal", "te", "te", "va"]`, tendremos como salida `['hola-qué', 'qué-tal', 'tal-te', 'te-va']`

In [104]:
def bigramas(l):
    return [l[i]+"-"+l[i+1] for i in range(len(l)-1) if l[i]!=l[i+1]]

bigramas(["hola","qué", "tal", "te",  "te", "va"])

['hola-qué', 'qué-tal', 'tal-te', 'te-va']

**Ejercicio 10** (largo) Ahora queremos relacionar bigramas de palabras unos con otros (es decir, 4 elementos, 2 con 2). Para ello vamos a repetir buena parte del código de la práctica pero adaptada 

1) aplicamos bigramas a palabras, lo que da una variable bi

2) Contamos los N elementos más frecuentes en bi, a los que podemos llamar `bifrecuentes`

3) Escribimos una función `bigramasEnFrase`, que dada una lista de bigramas y una frase devuelve una lista de 1s  y 0s indicando qué bigramas están en una frase. Nota: Un bigrama está en una frase si están las dos palabras que lo componen

4) Aplicamos la función con `bifrecuentes`y cada frase en `frases` lo que nos dará una lista de listas `bipertenencia`

5) Con `bipertenencia` creamos un dataframe `df_bi`, del que quitamos las filas que tengan todo 0s dando lugar a `df2_bi`

6) Calculamos las correlaciones en  `df2_bi` y mostramos las parejas de bigramas que tengan una correlación mayor que 0.10 en valor absoluto (rebajamos la exigencia de 0.25 a 0.10). Solo debemos mostrar parejas de bigramas que no tengan ninguna palabra en común, es decir deben representar 4 palabras distintas.

In [106]:
# solución
bi = bigramas (palabras)

N=25
c = Counter(bi)
bifrecuentes = [p for p,_ in c.most_common(N)]

def bigramasEnFrase(bigramas,frase):
    # solución
    return [ 0 if (p.split("-")[0] not in frase) or (p.split("-")[1] not in frase) else 1 for p in bigramas]

bipertenencia = [bigramasEnFrase(bifrecuentes,f) for f in frases]


df_bi = pd.DataFrame(bipertenencia,columns=bifrecuentes)

df2_bi = df_bi[df_bi!=0].dropna(how="all").fillna(0).reset_index(drop=True)

correlaciones = df2_bi.corr()
for c1 in df2_bi.columns:
    for c2 in df2_bi.columns:
        if c1<c2 and set(c1.split("-")).intersection(c2.split("-"))==set():
            v = correlaciones.loc[c1,c2]
            if abs(v)>0.10:
                print(c1,c2,v)

AGUA-SAL HUEVO-AZÚCAR -0.15518432973935514
AJO-PEREJIL YEMA-HUEVO -0.1114482683078044
AJO-PEREJIL HUEVO-AZÚCAR -0.10671286285524281
AJO-PEREJIL MIGA-PAN 0.11089282824629997
HUEVO-AZÚCAR SAL-MANTECA -0.15533375783061953
HUEVO-AZÚCAR SAL-AJO -0.11123262914600116
HUEVO-AZÚCAR PEREJIL-SAL -0.14616332401395338
ACEITE-VINAGRE AGUA-SAL 0.10740167186406366
AZÚCAR-CANELA PEREJIL-SAL -0.1133433514965353
HARINA-HUEVO SAL-AJO -0.10279400210332003
ACEITE-AJO HARINA-HUEVO -0.1084110240392176
ACEITE-AJO PEREJIL-SAL 0.14800155150416155
ACEITE-AJO MANTECA-HARINA -0.10266713466606818
ACEITE-MANTECA AJO-PEREJIL 0.10551856977336163
ACEITE-MANTECA MIGA-PAN 0.10721377062050283
SAL-AJO YEMA-HUEVO -0.11007370451274437
HUEVO-SAL MIGA-PAN 0.12978349837305359
AZÚCAR-HARINA SAL-MANTECA -0.1145128037469699
AZÚCAR-HARINA SAL-AJO -0.1098361679754799
AZÚCAR-HARINA PEREJIL-SAL -0.11089375037568948
ACEITE-CEBOLLA AJO-PEREJIL 0.14781071370799545
ACEITE-CEBOLLA SAL-AJO 0.11399736512411375