<table>
<tr>
<td><img src="https://raw.githubusercontent.com/RafaelCaballero/APD/refs/heads/main/img/logoAPD.png" width="150"></td>
<td><table><tr><td><h1>Pandas - Agregaciones</h1></td></tr>
           <tr><td><h3>Rafael Caballero Roldán</h3></td></tr></table></td>
<td><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsPjCdm67xYS9AM7-dXQ46O23vaexAhnVJaQ&s" width="105"></td>
</tr>
</table>


[Groupby](#Groupby)<br>

[Multinivel](#Multinivel)<br>

[pivot_table](#pivot_table)

<a id="Groupby"></a>
## Groupby




Consideramos el siguiente dataframe:

In [4]:
import pandas as pd
datos = [
    { "nombre": "Bertoldo", "mes": "Marzo", "distKm": 6,  "tiempoMin": 42,  "comp": False},
    { "nombre": "Herminia", "mes": "Marzo", "distKm": 10, "tiempoMin": 60,  "comp": True},
    { "nombre": "Bertoldo", "mes": "Marzo", "distKm": 2,  "tiempoMin": 12,  "comp": False},
    { "nombre": "Herminia", "mes": "Marzo", "distKm": 10, "tiempoMin": 61,  "comp": True},
    { "nombre": "Bertoldo", "mes": "Abril", "distKm": 5,  "tiempoMin": 33,  "comp": False},
    { "nombre": "Herminia", "mes": "Abril", "distKm": 42, "tiempoMin": 285, "comp": True},
    { "nombre": "Aniceto",  "mes": "Abril", "distKm": 5,  "tiempoMin": 33,  "comp": False},
]

df = pd.DataFrame(datos)
df

     nombre    mes  distKm  tiempoMin   comp
0  Bertoldo  Marzo       6         42  False
1  Herminia  Marzo      10         60   True
2  Bertoldo  Marzo       2         12  False
3  Herminia  Marzo      10         61   True
4  Bertoldo  Abril       5         33  False
5  Herminia  Abril      42        285   True
6   Aniceto  Abril       5         33  False

Nosotras sabemos ya calcular la distancia media:

In [5]:
df["distKm"].mean()

np.float64(11.428571428571429)

Pero ¿y si queremos la distancia media **por nombre**? Una opción sería dividir el dataframe en varios, uno por nombre distinto y calcular allí las medias. Por fortuna no tenemos que hacer esto; Pandas ya se encarga de hacerlo por nosotros

In [7]:
media_por_nombre = df.groupby("nombre")["distKm"].mean()
media_por_nombre

nombre
Aniceto      5.000000
Bertoldo     4.333333
Herminia    20.666667
Name: distKm, dtype: float64

Lo que hace esta instrucción es:

1) Crea los grupos con `df.groupby("nombre")`

In [11]:
df.groupby("nombre")

In [10]:
for nombre, g in df.groupby("nombre"):
    print("\n=== Grupo:", nombre, "===")
    print(g)

=== Grupo: Aniceto ===
    nombre    mes  distKm  tiempoMin   comp
6  Aniceto  Abril       5         33  False

=== Grupo: Bertoldo ===
     nombre    mes  distKm  tiempoMin   comp
0  Bertoldo  Marzo       6         42  False
2  Bertoldo  Marzo       2         12  False
4  Bertoldo  Abril       5         33  False

=== Grupo: Herminia ===
     nombre    mes  distKm  tiempoMin  comp
1  Herminia  Marzo      10         60  True
3  Herminia  Marzo      10         61  True
5  Herminia  Abril      42        285  True

Ahora seleccionamos la columna que queremos y aplicamos la función de agregación que deseemos

In [14]:
df.groupby("nombre")["distKm"].mean()

nombre
Aniceto      5.000000
Bertoldo     4.333333
Herminia    20.666667
Name: distKm, dtype: float64

Con dos columnas:

In [29]:
media_por_nombre = df.groupby("nombre")[["distKm", "tiempoMin"]].mean()
media_por_nombre

             distKm   tiempoMin
nombre
Aniceto    5.000000   33.000000
Bertoldo   4.333333   29.000000
Herminia  20.666667  135.333333

¿Y qué ocurre si queremos aplicar un función diferente según cada columna? 

En este caso usaremos `agg`

<a id="Multinivel"></a>
## Multinivel

Ejercicio: seleccionar el `tiempoMin` máximo por nombre y mes

In [30]:
 df.groupby(["nombre","mes"])[ "tiempoMin"].max()

nombre    mes
Aniceto   Abril     33
Bertoldo  Abril     33
          Marzo     42
Herminia  Abril    285
          Marzo     61
Name: tiempoMin, dtype: int64

In [32]:
res = df.groupby(["nombre","mes"])[ ["tiempoMin"]].max()
res

                tiempoMin
nombre   mes
Aniceto  Abril         33
Bertoldo Abril         33
         Marzo         42
Herminia Abril        285
         Marzo         61

El resultado es un índice multinivel o "multiindex". La selección se sigue pudiendo hacer con loc:

In [26]:
res.loc[("Bertoldo", "Marzo"),:]

tiempoMin    42
Name: (Bertoldo, Marzo), dtype: int64

In [36]:
res.loc[(slice(None), "Marzo"),:]

                tiempoMin
nombre   mes
Bertoldo Marzo         42
Herminia Marzo         61

El `slice(None)` sustituye al : en índices multinivel

<a id="pivot_table"></a>
## pivot_table

[pivot_table](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html) Añade una función de agregación a pivot.

In [37]:
stocks = pd.read_csv('https://gist.githubusercontent.com/alexdebrie/b3f40efc3dd7664df5a20f5eee85e854/raw/ee3e6feccba2464cbbc2e185fb17961c53d2a7f5/stocks.csv')
stocks

          date symbol     open     high      low    close    volume
0   2019-03-01   AMZN  1655.13  1674.26  1651.00  1671.73   4974877
1   2019-03-04   AMZN  1685.00  1709.43  1674.36  1696.17   6167358
2   2019-03-05   AMZN  1702.95  1707.80  1689.01  1692.43   3681522
3   2019-03-06   AMZN  1695.97  1697.75  1668.28  1668.95   3996001
4   2019-03-07   AMZN  1667.37  1669.75  1620.51  1625.95   4957017
5   2019-03-01   AAPL   174.28   175.15   172.89   174.97  25886167
6   2019-03-04   AAPL   175.69   177.75   173.97   175.85  27436203
7   2019-03-05   AAPL   175.94   176.00   174.54   175.53  19737419
8   2019-03-06   AAPL   174.67   175.49   173.94   174.52  20810384
9   2019-03-07   AAPL   173.87   174.44   172.02   172.50  24796374
10  2019-03-01   GOOG  1124.90  1142.97  1124.75  1140.99   1450316
11  2019-03-04   GOOG  1146.99  1158.28  1130.69  1147.80   1446047
12  2019-03-05   GOOG  1150.06  1169.61  1146.19  1162.03   1443174
13  2019-03-06   GOOG  1162.49  1167.57  1155.49  1157.86   1099289
14  2019-03-07   GOOG  1155.72  1156.76  1134.91  1143.30   1166559

Vamos a convertir la columna `symbol`en 3, una para cada uno de sus valores

In [38]:
df_symbol = stocks.pivot(index='date', columns='symbol', values='volume')
df_symbol

symbol          AAPL     AMZN     GOOG
date
2019-03-01  25886167  4974877  1450316
2019-03-04  27436203  6167358  1446047
2019-03-05  19737419  3681522  1443174
2019-03-06  20810384  3996001  1099289
2019-03-07  24796374  4957017  1166559

¿Y qué sucede si el índice se repite? Pues que pivot_table hace utiliza una función de agregación, por defecto la suma

In [39]:
stocks.pivot_table(index='symbol', values='volume')

            volume
symbol
AAPL    23733309.4
AMZN     4755355.0
GOOG     1321077.0

Ahora añadimos una función de agregación de forma explícita

In [ ]:
import numpy as np
stocks.pivot_table(index='symbol', values='volume', aggfunc="sum")

C:\Users\Rafa\AppData\Local\Temp\ipykernel_26156\2411833098.py:2: FutureWarning: The provided callable <function sum at 0x000002E35F3658A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  stocks.pivot_table(index='symbol', values='volume', aggfunc=np.sum)

           volume
symbol
AAPL    118666547
AMZN     23776775
GOOG      6605385

In [42]:
import numpy as np
stocks.pivot_table(index='symbol', values='volume', aggfunc="mean")

            volume
symbol
AAPL    23733309.4
AMZN     4755355.0
GOOG     1321077.0